version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./app:/var/www/html"
        ports:
            - "8010:80"
        restart: always
        depends_on:
            - php
    php:
        image: php:7.2-fpm
        restart: always
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./app:/var/www/html"
