version: '3'
services:
    web:
        build: ./
        image: simplon_server
        container_name: simplon_web
        volumes:
            - "./app:/var/www/html"
        ports:
            - "8010:80"
        restart: always
        depends_on:
            - php
    php:
        image: nanoninja/php-fpm:7.2
        container_name: simplon_php
        restart: always
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./app:/var/www/html"
